### ISSUE TITLE
<url> ссылка на товар

### ISSUE THREAD

**Issue by anboo** [retailcrm/moyskad-catalog#12]
А каким образом я могу сделать так, чтобы в RetailCRM была ссылка на товар именно в нашем магазине, а в системе МойСклад?
http://joxi.ru/GrqKPQlHd8z32z

**Comment by dmamontov** [comment]
Создайте кастомное поле в моем складе и заполните ссылки на товары в магазине. А так же немного доработайте скрипт чтобы он выбирал это свойство и дописывал в нужное место.
