### ISSUE TITLE
Не работает скрипт

### ISSUE THREAD

**Issue by LoginovDV** [retailcrm/moyskad-catalog#18]
Установил скрипт по инструкции, пытаюсь сгенерировать выдает ошибки.
Notice: Undefined index: rows in /var/www/vh283875/data/www/new.deepersonar.ru/moysklad/MoySkladICMLParser.php on line 191 Notice: Undefined index: meta in /var/www/vh283875/data/www/new.deepersonar.ru/moysklad/MoySkladICMLParser.php on line 314 Notice: Undefined index: rows in /var/www/vh283875/data/www/new.deepersonar.ru/moysklad/MoySkladICMLParser.php on line 133 Warning: Invalid argument supplied for foreach() in /var/www/vh283875/data/www/new.deepersonar.ru/moysklad/MoySkladICMLParser.php on line 133 Notice: Undefined index: meta in /var/www/vh283875/data/www/new.deepersonar.ru/moysklad/MoySkladICMLParser.php on line 165 Notice: Undefined variable: categories in /var/www/vh283875/data/www/new.deepersonar.ru/moysklad/MoySkladICMLParser.php on line 175

**Comment by azgalot** [comment]
Добрый день.
Проанализировали ошибки - не смогли найти соответствия в ошибках по индексам с позициями строк.
Обратитесь, пожалуйста, в нашу техническую поддержку с данной проблемой. Также, по возможности, приложите к сообщению используемый Вами файл MoySkladICMLParser.php.
