### ISSUE TITLE
Ошибка 504 при выгрузке изображений в imgur

### ISSUE THREAD

**Issue by gladich** [retailcrm/moyskad-catalog#23]
Возникает ошибка 504 при выгрузке изображений в imgur ( слишком долго грузит скрипт ), на VPS сервере работает но не все изображения попадают в xml, не создается файл images/**.json

**Comment by sergeygw1990** [comment]
imgur ужесточил правила на использование ресурса. При загрузке большого количества изображений. На данный момент над скриптом генерации ведуться работы для решения данной проблемы. В скором времени будет обновление скрипта.
